project:
  type: website
  output-dir: docs

website:
  title: "Hanbo Dai"
  navbar:
    left:
      - href: index.qmd
        text: 首页
      - href: about.qmd
        text: 关于我
      - href: projects.qmd
        text: 项目

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
